#' Select Function to Compute Preference Order
#'
#' @description
#' Internal function to select a proper f_...() function to compute preference order depending on the types of the response variable and the predictors. The selection criteria is available as a data frame generated by [default_f_heuristic()].
#'
#'
#' @inheritParams collinear
#' @return function
#' @family preference_order
#' @export
#' @autoglobal
#' @examples
#' TODO
default_f <- function(
    df = NULL,
    response = NULL,
    predictors = NULL
    ){

  if(is.null(df) || is.null(response) || is.null(predictors)) {
    return(NULL)
  }

  #data frame with heuristic
  heuristic <- default_f_heuristic()

  response_type <- identify_response_type(
    df = df,
    response = response
    )

  if(response_type == "unknown"){
    stop(
      "collinear::select_f(): response type is 'unknown', please select an f_...() function suitable for your response data.",
      call. = FALSE
    )
  }

  predictors_type <- identify_predictors_type(
    df = df,
    predictors = predictors
  )

  if(predictors_type == "unknown"){
    stop(
      "collinear::select_f(): predictors type is 'unknown', please select an f_...() function suitable for your predictor data.",
      call. = FALSE
    )
  }

  #select function
  f_name <- heuristic[
    heuristic$response_type == response_type &
      heuristic$predictors_type == predictors_type,
    "name"
    ]

  message(
    "collinear::select_f(): selected function to compute preference order is: '",
    f_name,
    "()'."
  )

  get(f_name)

}


#' Heuristic to Select Default Function to Compute Preference Order
#'
#' @description
#' Data frame with rules used by [default_f()] to select the function f_...() used to compute preference order in [preference_order()].
#'
#'
#' @return data frame
#' @family preference_order
#' @export
#' @autoglobal
#' @examples
#' default_f_heuristic()
default_f_heuristic <- function(){

  data.frame(
    name = c(
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_pearson",
      "f_r2_rf",
      "f_r2_rf",
      "f_auc_rf",
      "f_auc_rf",
      "f_auc_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_r2_rf",
      "f_v_rf_categorical",
      "f_v",
      "f_v_rf_categorical"
    ),
    response_type = c(
      "continuous-binary",
      "continuous-binary",
      "continuous-binary",
      "continuous-low",
      "continuous-low",
      "continuous-low",
      "continuous-high",
      "continuous-high",
      "continuous-high",
      "integer-binomial",
      "integer-binomial",
      "integer-binomial",
      "integer-binary",
      "integer-binary",
      "integer-binary",
      "integer-low",
      "integer-low",
      "integer-low",
      "integer-high",
      "integer-high",
      "integer-high",
      "categorical",
      "categorical",
      "categorical"
    ),
    predictors_type = c(
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed",
      "numeric",
      "categorical",
      "mixed"
    )
  )

}

