# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "x", # <cor_df>
  "y", # <cor_df>
  "correlation", # <cor_df>
  "Var1", # <cor_numerics>
  "Var2", # <cor_numerics>
  "Freq", # <cor_numerics>
  "x", # <cor_numerics>
  "y", # <cor_numerics>
  "pair_name", # <cor_numerics>
  "response", # <cor_numerics_and_characters>
  "var", # <identify_zero_variance_predictors>
  "encoded", # <target_encoding_rnorm>
  "is.required", # <validate_response>
  "vif", # <vif_df>
  "variable", # <vif_select>
  "vif", # <vif_select>
  NULL
))
