# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <cor_df>
  # <cor_numerics>
  "correlation",
  # <cor_numerics>
  "Freq",
  # <response_inspect>
  "is.required",
  # <cor_numerics>
  "pair_name",
  # <predictors_zero_variance>
  "var",
  # <cor_numerics>
  "Var1",
  # <cor_numerics>
  "Var2",
  # <vif_select>
  "variable",
  # <vif_df>
  # <vif_select>
  "vif",
  # <cor_numerics>
  "x",
  # <cor_numerics>
  "y",
  NULL
))
