# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "quiet", # <target_encoding_rank>
  "quiet", # <target_encoding_loo>
  "predictors.numeric", # <validate_data_cor>
  NULL
))
